version: '3.8'

services:
  postgres-compose:
    image: postgres
    networks:
      - iw-network
    ports:
      - "9432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=progresssoft_db
  progresssoft:
    image: vinlyreeks/progresssoft:1.0.0
    depends_on:
      - postgres-compose
    networks:
      - iw-network
    deploy:
      restart_policy:
        condition: on-failure
        delay: 50s
        max_attempts: 3
        window: 120s
    ports:
      - "8090:8080"
    environment:
      DB_HOST:  postgres-compose
      DB_DRIVER: org.postgresql.Driver
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: progresssoft_db
      DB_PORT: 5432

networks:
  iw-network:

