spring:
  application:
    name: data-cluster-service
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: true
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:6432}/${DB_NAME:progresssoft_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
logging:
  level:
    org.hibernate.SQL: DEBUG
    com.data.warehouse: DEBUG

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers']
